repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        additional_dependencies: ["ruamel.yaml>=0.18.0"]
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
      - id: script-must-have-extension
        exclude: \.envrc$
      - id: script-must-not-have-extension
      - id: shellcheck
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        description: Format Rust code with rustfmt
        entry: cargo fmt
        language: system
        pass_filenames: false
        types: [rust]
      - id: clippy
        name: cargo clippy
        description: Lint Rust code with clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]
      - id: cargo-check
        name: cargo test
        description: Run Rust tests
        entry: cargo test
        language: system
        pass_filenames: false
        types: [rust]
